site_name: Harvard FAS Informatics Group
nav:
  - Home: index.md
  - About: 
    - about/index.md
  - Resources: 
    - resources/index.md
    - Python: resources/python.md
    - R: 
      - Part 1: resources/R_Workshop/R-workshop-2023-Part1.md
      - Part 2: resources/R_Workshop/R-workshop-2023-Part2.md
      - Part 3: resources/R_Workshop/R-workshop-2023-Part3.md
  - Research: research/index.md
  - Software: software/index.md
  - Contact Us: contact.md
  - Events: events.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline 
      name: Switch to dark mode
    primary: red
    accent: grey 
  - scheme: slate 
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode    
    primary: salmon
    accent: black
extra_css:
  - stylesheets/extra.css