site_name: Harvard FAS Informatics Group

### Example Configuration ###

# Custom Homepage Elements
home_cover_image: ../img/fas-info-logo-old.png # This path starts at your root mkdocs directory.
home_tagline: FAS Informatics
home_description: |
  Bioinformatics training, collaboration, and research

# Gradient Color
home_gradient_hsla: hsla(1deg,82%,20%,1) # Default Green: hsla(160deg,47%,55%,1)

# Custom Homepage Button(s)
home_button1_name: Research                  # Comment this parameter out to remove the button.
home_button1_url: ../research/                       # This path starts at your root mkdocs directory.
home_button1_theme: md-button md-button--primary # Options: "md-button", "md-button md-button--primary"
home_button1_icon: people                        # Options: "people", "gear", "image"
home_button1_blurb: |                            # Short description of this button / section.
  Learn about our group's goals and the people who make up the FAS Informatics Group

home_button2_name: Resources   # Comment this parameter out to remove the button.
home_button2_url: ../resources/    # This path starts at your root mkdocs directory.
home_button2_theme: md-button # Options: "md-button", "md-button md-button--primary"
home_button2_icon: gear       # Options: "people", "gear", "image"
home_button2_blurb: |         # Short description of this button / section.
  Workshops, tutorials, and other resources for learning bioinformatics

home_button3_name: Software   # Comment this parameter out to remove the button.
home_button3_url: ../software/    # This path starts at your root mkdocs directory.
home_button3_theme: md-button # Options: "md-button", "md-button md-button--primary"
home_button3_icon: gear      # Options: "people", "gear", "image"
home_button3_blurb: |         # Short description of this button / section.
  Software developed by the FAS Informatics Group

copyright: © 2023 | Harvard FAS Informatics

nav:
  - Home: 
    - index.md
  - Resources: 
    - resources/index.md
    - Workshops:
      - R: 
        - Introduction: resources/Workshops/R/index.html
        - Get started: resources/Workshops/R/start.html
        - Part 1: resources/Workshops/R/R-workshop-2023-Part1.md
        - Part 2: resources/Workshops/R/R-workshop-2023-Part2.md
        - Part 3: resources/Workshops/R/R-workshop-2023-Part3.md
      - Unix: 
        - Introduction: resources/Workshops/Unix/index.html
        - Get started: resources/Workshops/Unix/start.html
        - Part 1: resources/Workshops/Unix/Biotips-workshop-2023-Day1.md
        - Part 2: resources/Workshops/Unix/Biotips-workshop-2023-Day2.md
        - Part 3: resources/Workshops/Unix/Biotips-workshop-2023-Day3.md
        - Part 4: resources/Workshops/Unix/Biotips-workshop-2023-Day4.md
  - Research: research/index.md
  - Software: software/index.md
  - FAQ: faq/index.md
  - Contact Us: contact.md
  - Events: events.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
theme: 
  name: material
  custom_dir: docs/assets
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.annotation
    - content.code.copy
  language: en
  favicon: img/Icon_favicon.png
  logo: img/Icon_bw.png
  palette:
    scheme: default
    primary: red
    accent: grey   
    # toggle:
    #   icon: material/toggle-switch-off-outline 
    #   name: Switch to dark mode

  # - scheme: slate 
  #   toggle:
  #     icon: material/toggle-switch
  #     name: Switch to light mode    
  #   primary: salmon
  #   accent: black
plugins:
  - search
  - table-reader
hooks:
  - scripts/about_generator.py 
  - scripts/resources_generator.py 
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/harvardinformatics/
    - icon: fontawesome/brands/slack
      link: https://fas-bioinformaticspub.slack.com/
    - icon: material/email-outline
      link: https://forms.office.com/r/qwXEPbBvFK    