site_name: Harvard FAS Informatics Group
copyright: © 2023-2025 | Harvard FAS Informatics | <a href="https://accessibility.huit.harvard.edu/digital-accessibility-policy">Digital Accessibility</a>
## Site info

nav:
  - Home: 
    - index.md
  - Workshops: workshops/index.md
  - Research: research/index.md
  - Software: software/index.md
  - Resources: resources/index.md
  - FAQ: faq/index.md
  - Contact Us: contact.md
  - Events: events.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - docs/assets/.icons
theme: 
  name: material
  custom_dir: docs/assets
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.annotation
    - content.code.copy
  language: en
  favicon: img/Icon_bw.png
  logo: img/fas-shield-logo.png
  palette:
    scheme: default
    primary: custom
    accent: grey   
    # toggle:
    #   icon: material/toggle-switch-off-outline 
    #   name: Switch to dark mode
    ## For dark mode

  # - scheme: slate 
  #   toggle:
  #     icon: material/toggle-switch
  #     name: Switch to light mode    
  #   primary: salmon
  #   accent: black
  ## Dark mode
plugins:
  - search
  - table-reader
  - mkdocs-jupyter:
      ignore: ['*student.ipynb']
hooks:
  - scripts/about_generator.py 
  - scripts/resources_generator.py 
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: material/email-outline
      link: https://forms.office.com/r/qwXEPbBvFK
      name: FAS Informatics Contact Form
    - icon: fontawesome/brands/slack
      link: https://fas-bioinformaticspub.slack.com/
      name: FAS Informatics Slack channel
    - icon: fontawesome/brands/github
      link: https://github.com/harvardinformatics/
      name: FAS Informatics GitHub
    - icon: material/newspaper-plus
      link: /newsletter/
      name: FAS Informatics Newsletter      
    - icon: material/dna
      link: https://bauercore.fas.harvard.edu/  
      name: FAS Bauer Core Facility
    - icon: custom/fas-rc-logo
      link: https://www.rc.fas.harvard.edu/
      name: FAS Research Computing
    - icon: custom/fas-shield-logo
      link: https://www.fas.harvard.edu/
      name: Harvard FAS
    ## Paths to bundled icons: https://github.com/squidfunk/mkdocs-material/tree/cca090bebb14e9f762984d88abb3707c3ea203d8/material/templates/.icons


### The following configures the buttons and image on the home page ###
### Modified from https://github.com/tylerdotrar/mkdocs-coverpage ###
### The icon and blurb parameters were used for the bottom buttons on the home page which we omit ###

# Custom Homepage Elements
home_cover_image: img/Icon_bw.png # This path starts at your root mkdocs directory.
home_tagline: FAS Informatics
home_description: Bioinformatics training, collaboration, and research

# Gradient Color
home_gradient_hsla: hsla(1deg,82%,20%,1) # Default Green: hsla(160deg,47%,55%,1)

# Custom Homepage Button(s)
home_button1_name: FAQ                  # Comment this parameter out to remove the button.
home_button1_url: faq/                       # This path starts at your root mkdocs directory.
home_button1_theme: md-button # Options: "md-button", "md-button md-button--primary"
#home_button1_icon: people                        # Options: "people", "gear", "image"
#home_button1_blurb: |                            # Short description of this button / section.
#  Learn about our group's goals and the people who make up the FAS Informatics Group

home_button2_name: Workshops   # Comment this parameter out to remove the button.
home_button2_url: workshops/    # This path starts at your root mkdocs directory.
home_button2_theme: md-button # Options: "md-button", "md-button md-button--primary"
#home_button2_icon: gear       # Options: "people", "gear", "image"
#home_button2_blurb: |         # Short description of this button / section.
#  Workshops, tutorials, and other resources for learning bioinformatics

home_button3_name: Contact&nbsp;Us   # Comment this parameter out to remove the button.
home_button3_url: contact    # This path starts at your root mkdocs directory.
home_button3_theme: md-button # Options: "md-button", "md-button md-button--primary"
#home_button3_icon: gear      # Options: "people", "gear", "image"
#home_button3_blurb: |         # Short description of this button / section.
#  Software developed by the FAS Informatics Group
