site_name: Harvard FAS Informatics Group
nav:
  - Home: index.md
  - About: 
    - about/index.md
    - about/people/timsackton.md
  - Resources: 
    - resources/index.md
    - Workshops:
      - R: 
        - Introduction: resources/Workshops/R/index.html
        - Get started: resources/Workshops/R/start.html
        - Part 1: resources/Workshops/R/R-workshop-2023-Part1.md
        - Part 2: resources/Workshops/R/R-workshop-2023-Part2.md
        - Part 3: resources/Workshops/R/R-workshop-2023-Part3.md
      - Unix: 
        - Introduction: resources/Workshops/Unix/index.html
        - Get started: resources/Workshops/Unix/start.html
        - Part 1: resources/Workshops/Unix/Biotips-workshop-2023-Day1.md
        - Part 2: resources/Workshops/Unix/Biotips-workshop-2023-Day2.md
        - Part 3: resources/Workshops/Unix/Biotips-workshop-2023-Day3.md
        - Part 4: resources/Workshops/Unix/Biotips-workshop-2023-Day4.md
  - Research: research/index.md
  - Software: software/index.md
  - Contact Us: contact.md
  - Events: events.md
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline 
      name: Switch to dark mode
    primary: red
    accent: grey 
  - scheme: slate 
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode    
    primary: salmon
    accent: black
plugins:
  - search
  - table-reader
hooks:
  - scripts/about_generator.py 
  - scripts/resources_generator.py 
extra_css:
  - stylesheets/extra.css
