site_name: Harvard FAS Informatics Group
site_url: https://informatics.fas.harvard.edu/
copyright: © 2023-2025 | Harvard FAS Informatics | <a href="https://accessibility.huit.harvard.edu/digital-accessibility-policy">Digital Accessibility</a>
## Site info

nav: 
  - Home: index.md
  - Events & Workshops: events-workshops/index.md
  - Research & Publications: research/index.md
  - Software: software/index.md
  - Resources: resources/index.md
  - FAQ: faq/index.md
  - Contact Us: contact/index.md

# This is a list of files that will not be included in the navigation bar, but will still be built by MkDocs.
# Having this prevents the message listing these files when building the site
not_in_nav: | 
  newsletter.md  
  people/*
  events-workshops/previous-events.md
  resources/tutorials/*.md
  resources/glossary.md
  resources/tags/*.md
  workshops/
  _includes/*

markdown_extensions:
  - admonition  
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - docs/assets/.icons 

theme: 
  name: material 
  custom_dir: docs/assets
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.annotation
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.footer.last-update  # Shows the last update in the footer    
  language: en
  favicon: img/fasifx/Icon_bw.png 
  logo: img/fasifx/fas-shield-logo.png
  palette:
    scheme: default
    primary: custom
    accent: grey   
    # toggle:
    #   icon: material/toggle-switch-off-outline 
    #   name: Switch to dark mode
    ## For dark mode

  # - scheme: slate 
  #   toggle:
  #     icon: material/toggle-switch
  #     name: Switch to light mode    
  #   primary: salmon
  #   accent: black
  ## Dark mode

plugins:
  - search
  - table-reader  
  - macros:      # This plugin allows you to run Python macros to insert content onto pages as the site is built use Jinja2-style; see scripts/macros.py for implemented macros.
      module_name: scripts/macros
      # verbose: true # MACRO DEBUG: Uncomment for debugging (use chatter() in macros)
  - gen-files:   # This plugin generates files from templates and data files
      scripts: 
        - scripts/about_generator.py 
        - scripts/tags_generator.py
        - scripts/profile_generator.py 
  # - mkdocs-jupyter: # mkdocs-jupyter==0.24.7, succeeded by jupyter_convert hook
  #     ignore: 
  #       - '*student.ipynb' 
  #       - '2024-Fall/Python-Day*.ipynb'
  #       - '*.ipynb' # for development, uncomment this line to prevent building all notebooks with each change. be sure to re-comment before pushing to remote (though re-commenting now handled with pre-commit hooks).
  - git-revision-date-localized:  # This plugin adds the last updated date to the footer of each page
      timezone: America/New_York
      enable_creation_date: true
      exclude:
        - 'resources/tags/*'
        - '_includes/*'
        - 'people/*' 
  - social:
      cards_layout_options:
        background_color: "#F3F4F4" 
        color: "#a51c30"
        font_family: Open Sans
        # font_family: DM Sans

hooks:
  - scripts/jupyter_convert.py 

extra_css:
  - css/extra.css
  - css/author-row.css
  - css/banner.css
  - css/cards.css
  - css/grid.css
  - css/profile-header.css
  - css/software-logos.css
  - css/tags.css

extra_javascript:
  - js/collapse_toc.js
  - js/banner_img.js

extra:
  social:
    - icon: material/email-outline
      link: https://forms.office.com/r/qwXEPbBvFK
      name: FAS Informatics Contact Form
    - icon: fontawesome/brands/slack
      link: https://fas-bioinformaticspub.slack.com/
      name: FAS Informatics Slack channel
    - icon: fontawesome/brands/github
      link: https://github.com/harvardinformatics/
      name: FAS Informatics GitHub
    - icon: material/newspaper-plus
      link: /contact/newsletter/
      name: FAS Informatics Newsletter      
    - icon: material/dna
      link: https://bauercore.fas.harvard.edu/  
      name: FAS Bauer Core Facility
    - icon: custom/fas-rc-logo
      link: https://www.rc.fas.harvard.edu/
      name: FAS Research Computing
    - icon: custom/fas-shield-logo
      link: https://www.fas.harvard.edu/
      name: Harvard FAS
    ## Paths to bundled icons: https://github.com/squidfunk/mkdocs-material/tree/cca090bebb14e9f762984d88abb3707c3ea203d8/material/templates/.icons

  ##########

  ### The following configures the buttons and image on the home page ###
  ### Modified from https://github.com/tylerdotrar/mkdocs-coverpage ###
  ### The icon and blurb parameters were used for the bottom buttons on the home page which we omit ###

  # Custom Homepage Elements
  #home_cover_image: img/Icon_bw.png # This path starts at your root mkdocs directory.
  home_tagline: FAS Informatics
  home_description: Bioinformatics training, collaboration, and research

  # Gradient Color
  # home_gradient_hsla: hsla(1deg,82%,20%,1) # Default Green: hsla(160deg,47%,55%,1)

  # Custom Homepage Button(s)
  home_button1_name: Events             # Comment this parameter out to remove the button.
  home_button1_url: events-workshops/   # This path starts at your root mkdocs directory.
  home_button1_theme: md-button         # Options: "md-button", "md-button md-button--primary"

  home_button2_name: FAQ                # Comment this parameter out to remove the button.
  home_button2_url: faq/                # This path starts at your root mkdocs directory.
  home_button2_theme: md-button         # Options: "md-button", "md-button md-button--primary"

  home_button3_name: Contact&nbsp;Us    # Comment this parameter out to remove the button.
  home_button3_url: contact/            # This path starts at your root mkdocs directory.
  home_button3_theme: md-button         # Options: "md-button", "md-button md-button--primary"

